spring:
  application:
    name: loan-calculator

  datasource:
    url: jdbc:postgresql://localhost:5434/loan
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


