spring:
  application:
    name: loan-calculator

  datasource:
    url: jdbc:h2:mem:loandb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update


